-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bookings (
  id bigint NOT NULL DEFAULT nextval('bookings_id_seq'::regclass),
  booking_number text NOT NULL UNIQUE,
  item_id bigint NOT NULL,
  customer_id uuid NOT NULL,
  store_id bigint NOT NULL,
  booking_date date NOT NULL CHECK (booking_date >= CURRENT_DATE),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  duration_minutes integer NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text,
  notes text,
  price numeric NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::booking_status,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id),
  CONSTRAINT bookings_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.business_directory_tunisia (
  id bigint NOT NULL DEFAULT nextval('business_directory_tunisia_id_seq'::regclass),
  business_name text NOT NULL,
  legal_name text,
  business_type text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['RESTAURANT'::text, 'RETAIL'::text, 'BEAUTY'::text, 'REPAIR'::text, 'HEALTH'::text, 'EDUCATION'::text, 'AUTO'::text, 'OTHER'::text])),
  sub_category text,
  activity_code text,
  activity_description text,
  governorate text NOT NULL,
  delegation text,
  locality text,
  address text,
  postal_code text,
  latitude numeric,
  longitude numeric,
  phone text CHECK (phone ~ '^\+216[0-9]{8}$'::text OR phone IS NULL),
  phone_secondary text,
  email text CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text OR email IS NULL),
  website text,
  creation_date date,
  legal_status text DEFAULT 'ACTIF'::text CHECK (legal_status = ANY (ARRAY['ACTIF'::text, 'SUSPENDU'::text, 'RADIE'::text])),
  capital numeric,
  manager_name text,
  manager_role text,
  employee_count integer,
  employee_range text,
  description text,
  tags ARRAY,
  verified boolean DEFAULT false,
  data_source text,
  is_claimed boolean DEFAULT false,
  claimed_at timestamp with time zone,
  claimed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_verified_at timestamp with time zone,
  CONSTRAINT business_directory_tunisia_pkey PRIMARY KEY (id),
  CONSTRAINT business_directory_tunisia_claimed_by_fkey FOREIGN KEY (claimed_by) REFERENCES public.users(id)
);
CREATE TABLE public.items (
  id bigint NOT NULL DEFAULT nextval('items_id_seq'::regclass),
  store_id bigint NOT NULL,
  item_type USER-DEFINED NOT NULL DEFAULT 'PRODUCT'::item_type,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  price numeric NOT NULL,
  price_unit character varying NOT NULL DEFAULT 'unit'::character varying CHECK (price_unit::text = ANY (ARRAY['unit'::character varying, 'hour'::character varying, 'day'::character varying, 'session'::character varying]::text[])),
  stock_quantity integer,
  duration_minutes integer,
  is_bookable boolean DEFAULT false,
  available_days jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'AVAILABLE'::item_status,
  main_image text NOT NULL,
  image_2 text,
  image_3 text,
  view_count integer DEFAULT 0,
  order_count integer DEFAULT 0,
  booking_count integer DEFAULT 0,
  rating_average numeric DEFAULT 0.0,
  total_reviews integer DEFAULT 0,
  embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT items_pkey PRIMARY KEY (id),
  CONSTRAINT items_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.orders (
  id bigint NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
  order_number text NOT NULL UNIQUE,
  customer_id uuid,
  store_id bigint NOT NULL,
  item_id bigint,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text,
  delivery_address text NOT NULL,
  customer_notes text,
  vendor_notes text,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::order_status,
  tracking_code text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  validated_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id),
  CONSTRAINT orders_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT orders_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE TABLE public.reviews (
  id bigint NOT NULL DEFAULT nextval('reviews_id_seq'::regclass),
  author_id uuid NOT NULL,
  item_id bigint,
  store_id bigint NOT NULL,
  order_id bigint,
  booking_id bigint,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  comment text NOT NULL,
  image_1 text,
  image_2 text,
  is_verified boolean DEFAULT false,
  qr_token text UNIQUE,
  qr_scanned_at timestamp with time zone,
  sentiment_score numeric,
  sentiment_label USER-DEFINED,
  vendor_response text,
  vendor_response_ai_suggestion text,
  responded_at timestamp with time zone,
  is_approved boolean DEFAULT true,
  is_spam boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id),
  CONSTRAINT reviews_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id),
  CONSTRAINT reviews_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.service_schedules (
  id bigint NOT NULL DEFAULT nextval('service_schedules_id_seq'::regclass),
  item_id bigint NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  max_bookings integer DEFAULT 1 CHECK (max_bookings > 0),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT service_schedules_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.stores (
  id bigint NOT NULL DEFAULT nextval('stores_id_seq'::regclass),
  owner_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  category USER-DEFINED NOT NULL DEFAULT 'OTHER'::store_category,
  phone text NOT NULL,
  email text,
  website text,
  address text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  city text NOT NULL,
  logo_url text,
  banner_url text,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::store_status,
  business_license_url text,
  id_card_url text,
  verification_notes text,
  rating_average numeric DEFAULT 0.0,
  total_reviews integer DEFAULT 0,
  total_orders integer DEFAULT 0,
  view_count integer DEFAULT 0,
  sentiment_positive_percent numeric DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  verified_at timestamp with time zone,
  business_directory_id bigint,
  business_registration text,
  rne text UNIQUE,
  CONSTRAINT stores_pkey PRIMARY KEY (id),
  CONSTRAINT stores_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id),
  CONSTRAINT stores_business_directory_id_fkey FOREIGN KEY (business_directory_id) REFERENCES public.business_directory_tunisia(id)
);
CREATE TABLE public.subscriptions (
  id bigint NOT NULL DEFAULT nextval('subscriptions_id_seq'::regclass),
  user_id uuid NOT NULL,
  plan_name text NOT NULL,
  price numeric DEFAULT 0,
  current_period_start timestamp with time zone NOT NULL,
  current_period_end timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE'::text,
  auto_renew boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'CLIENT'::user_role,
  full_name text,
  phone text,
  avatar_url text,
  latitude numeric,
  longitude numeric,
  city text,
  address text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);